
services:

  # --- PROXY INVERSO (MANEJO DE HTTPS) ---
  caddy_reverse_proxy:
    image: caddy:2-alpine
    container_name: caddy_proxy
    restart: unless-stopped
    ports:
      - "80:80"     # Redirige tráfico HTTP a HTTPS
      - "443:443"   # Tráfico HTTPS seguro
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile  # Configuración de rutas
      - caddy_data:/data                  # Guarda los certificados generados
      - caddy_config:/config
    networks:
      - frontend_tools
      - backend_ai

  portainer: #http://100.76.141.48:9443/
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - frontend_tools

  # --- Ingest Process Service
  ingest_service:
    build: 
      context: ./ingest_service
      dockerfile: Dockerfile
    container_name: ingestion_service
    volumes:
      - ./storage/raw:/app/storage/raw
    networks:
      - backend_ai
  # --- Clean Process Service
  clean_service:
    build: 
      context: ./clean_service
      dockerfile: Dockerfile
    container_name: cleaning_service
    volumes:
      - ./storage/clean:/app/storage/process
    #environment:
    #  - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    #  - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    networks:
      - backend_ai

  # --- BASE DE DATOS RELACIONAL (EL CEREBRO ESTRUCTURADO) ---
  
  postgres_db:
    image: postgres:15-alpine
    container_name: postgres_service
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_ai

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_ui
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres_db
    networks:
      - frontend_tools

  database_service:
    build: 
      context: ./database_service
      dockerfile: Dockerfile
    container_name: database_service
    volumes:
      - ./database_service:/app
    depends_on:
      postgres_db:
        condition: service_healthy
    networks:
      - backend_ai
  # --- BASE DE DATOS EN MEMORIA (EL CEREBRO DE PROCESAMIENTO RÁPIDO) ---
  redis:
    image: redis:7-alpine
    container_name: redis_service
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - backend_ai
  
  # --- MOTOR DE BÚSQUEDA Y ANÁLISIS DE TEXTO (EL CEREBRO DE PROCESAMIENTO PROFUNDO) ---

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: elasticsearch_service
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    networks:
      - backend_ai

  # --- SERVICIOS DE LLM Y VECTOR DB 

  ollama:
    image: ollama/ollama
    container_name: llm_Service
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./llm_Service/entrypoint.sh:/entrypoint.sh
    restart: unless-stopped
    environment:
      - MODEL_NAME=${MODEL_NAME}
      - OLLAMA_KEEP_ALIVE=24h
    entrypoint: ["/bin/bash", "/entrypoint.sh"]
    networks:
       - backend_ai
  
  chroma:
    image: chromadb/chroma
    container_name: chroma_service
    ports:
      - "11743:8000"
    volumes:
      - chroma_data:/chroma/data
    restart: unless-stopped
    networks:
       - backend_ai

  web:
    build:  #https://localhost:8000
      context: ./llm_Service
      dockerfile: Dockerfile
    container_name: fastapi_llm
    restart: always
    ports:
      - '8000:8000'
    volumes:
      - ./llm_Service:/app
    environment:
      - APP_ENV=docker
      - OLLAMA_HOST=ollama
      - CHROMA_HOST=chroma
      - MODEL_NAME=llama3.1:8b
      - PYTHONPATH=/app
    depends_on:
      ollama:
        condition: service_started
      chroma:
        condition: service_started
      postgres_db:
        condition: service_healthy
    networks:
       - backend_ai

volumes:
  ollama_data:
  chroma_data:
  postgres_data:
  portainer_data:
  redis_data:
  elastic_data:
  caddy_data:
  caddy_config:


networks:
  backend_ai:
    driver: bridge
  frontend_tools:
    driver: bridge



