
services:

    # --- MONITOREO Y LOGGING ---
  prometheus: #http://100.76.141.48:9090/query
    image: prom/prometheus
    container_name: prometheus_service
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - backend_ai
  
  # --- INTERFAZ DE VISUALIZACIÓN Y ANÁLISIS DE DATOS ---
  grafana: #http://100.76.141.48:3000/d/ad2qn7h/monitor?orgId=1&from=now-6h&to=now&timezone=browser
    image: grafana/grafana:latest
    container_name: grafana_service
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - backend_ai
  # --- EXPORTADOR DE MÉTRICAS DEL SISTEMA (CPU, MEMORIA, DISCO, ETC.) ---
  node_exporter:
    image: prom/node-exporter
    container_name: node_exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
    networks:
      - backend_ai

  # --- PROXY INVERSO (MANEJO DE HTTPS) ---
  caddy_reverse_proxy:
    image: caddy:2-alpine
    container_name: caddy_proxy
    restart: unless-stopped
    ports:
      - "80:80"     # Redirige tráfico HTTP a HTTPS
      - "443:443"   # Tráfico HTTPS seguro
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile  # Configuración de rutas
      - caddy_data:/data                  # Guarda los certificados generados
      - caddy_config:/config
    networks:
      - frontend_tools
      - backend_ai

  portainer: #http://100.76.141.48:9443/ Interfaz de gestión de contenedores Docker, útil para monitorear y administrar tus servicios de forma visual. Puedes acceder a ella en https://localhost:9443/ (o reemplaza localhost por la IP de tu máquina si estás accediendo desde otra). Es una herramienta muy útil para ver el estado de tus contenedores, logs, estadísticas de uso, etc.
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - frontend_tools

  # --- Ingest Process Service
  ingest_service:
    build: 
      context: ./ingest_service
      dockerfile: Dockerfile
    container_name: ingestion_service
    environment:
      - POSTGRES_HOST=postgres_service  
      - LLM_SERVICE_URL=http://web:8000/text/
    volumes:
      - ./ingest_service:/app 
      - ./storage/raw:/app/storage/raw
    networks:
      - backend_ai
    env_file:
      - .env
  # --- Clean Process Service
  clean_service:
    build: 
      context: ./clean_service
      dockerfile: Dockerfile
    container_name: cleaning_service
    volumes:
      - ./storage/clean:/app/storage/process
    #environment:
    #  - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    #  - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    networks:
      - backend_ai

  # --- BASE DE DATOS RELACIONAL (EL CEREBRO ESTRUCTURADO) ---
  
  postgres_db:
    image: ankane/pgvector:latest
    container_name: postgres_service
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          memory: 2G 
        reservations:
          memory: 512M
    volumes:
      - ./Data/postgres/:/var/lib/postgresql/data
    networks:
      - backend_ai
    env_file:
      - .env 

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_ui
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres_db
    networks:
      - frontend_tools

  database_service:
    build: 
      context: ./database_service
      dockerfile: Dockerfile
    container_name: database_service
    volumes:
      - ./database_service:/app
    depends_on:
      postgres_db:
        condition: service_healthy
    networks:
      - backend_ai
  # --- BASE DE DATOS EN MEMORIA (EL CEREBRO DE PROCESAMIENTO RÁPIDO) ---
  redis:
    image: redis:7-alpine
    container_name: redis_service
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    
    deploy:
      resources:
        limits:
          memory: 1200M # Redis es muy eficiente, 1GB sobra para strings/cache
    # ✅ Comando para limitar memoria y activar política de borrado automático
    command: [
      "redis-server", 
      "--maxmemory 1gb", 
      "--maxmemory-policy allkeys-lru", 
      "--appendonly yes"
    ]
    networks:
      - backend_ai
  
  # --- MOTOR DE BÚSQUEDA Y ANÁLISIS DE TEXTO (EL CEREBRO DE PROCESAMIENTO PROFUNDO) ---

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: elasticsearch_service
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms4g -Xmx4g # Asigna 4GB de RAM para Elasticsearch, ajusta según tus necesidades
      - bootstrap.memory_lock=true
    ports:
      - "9200:9200"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    deploy:
      resources:
        limits:
          memory: 8G # Elasticsearch puede consumir bastante RAM, asigna lo que tu máquina pueda manejar
    ulimits:
      memlock:
        soft: -1
        hard: -1
    # Añadimos esta capacidad para que Docker pueda gestionar el bloqueo
    cap_add:
      - IPC_LOCK
    networks:
      - backend_ai
  
  # --- INTERFAZ DE VISUALIZACIÓN Y ANÁLISIS DE DATOS ---
  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.2
    container_name: kibana_service
    restart: unless-stopped
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - backend_ai
  
  embedding_service:
    build: 
      context: ./embedding_service
      dockerfile: Dockerfile
    container_name: embedding_service
    restart: always
    ports:
      - "8002:8000"
    environment:
      - MODEL_NAME=${EMBEDING_MODEL} # Modelo ligero y rápido
      - DEVICE=cpu # Para Docker en Mac, CPU es lo más estable; MPS requiere config avanzada
    volumes:
      - ./embedding_service:/app
      # - cache_models:/root/.cache/torch # Para no descargar el modelo cada vez que reinicies
    networks:
      - backend_ai

  # --- SERVICIOS DE LLM Y VECTOR DB 

  # ollama:
  #   image: ollama/ollama
  #   container_name: llm_Service
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - ollama_data:/root/.ollama
  #     - ./llm_Service/entrypoint.sh:/entrypoint.sh
  #   restart: unless-stopped
  #   environment:
  #     - MODEL_NAME=${MODEL_NAME}
  #     - OLLAMA_KEEP_ALIVE=24h
  #   entrypoint: ["/bin/bash", "/entrypoint.sh"]
  #   networks:
  #      - backend_ai
  
  chroma:
    image: chromadb/chroma
    container_name: chroma_service
    ports:
      - "11743:8000"
    volumes:
      - chroma_data:/chroma/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G  # Suficiente para desarrollo local
    networks:
       - backend_ai

  web:
    build:  #https://localhost:8000
      context: ./llm_Service
      dockerfile: Dockerfile
    container_name: fastapi_llm
    restart: always
    ports:
      - '8000:8000'
    volumes:
      - ./llm_Service:/app
    extra_hosts:
      - "host.docker.internal:host-gateway" # Permite que el contenedor acceda a servicios en el host (como Ollama)
    environment:
      - APP_ENV=docker
      - OLLAMA_HOST=host.docker.internal # Permite que el contenedor acceda a Ollama en el host/ cambiar por ip cuando tengamos mac
      - CHROMA_HOST=chroma
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ELASTIC_HOST=http://elasticsearch:9200
      - MODEL_NAME=${MODEL_NAME}
      - PYTHONPATH=/app
    depends_on:
      #ollama:
      #  condition: service_started
      chroma:
        condition: service_started
      postgres_db:
        condition: service_healthy
    networks:
       - backend_ai
    env_file:
      - .env 

volumes:
  #ollama_data:
  chroma_data:
  postgres_data:
  portainer_data:
  redis_data:
  elastic_data:
  grafana_data:
  caddy_data:
  caddy_config:
 # cache_models:


networks:
  backend_ai:
    driver: bridge
  frontend_tools:
    driver: bridge



