
services:
  ollama:
    image: ollama/ollama
    container_name: llm_service
    ports:
      - "11434:11434"
    volumes:
      - C:/Users/carrie5/.ollama:/root/.ollama
    restart: unless-stopped
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    networks:
       - isolated_backend
  
  chroma:
    image: chromadb/chroma
    container_name: chroma_service
    ports:
      - "11743:8000"
    volumes:
      - chroma_data:/chroma/data
    restart: unless-stopped
    networks:
       - isolated_backend


  postgres:
    image: postgres:14-alpine
    container_name: DBTesting_compose
    environment:
      # Los mismos valores de tu comando docker run
      POSTGRES_USER: kcire
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: dbLLM
    ports:
      # Exponemos el puerto para que puedas conectarte desde tu máquina
      - "5433:5432"
    volumes:
      # Usamos el mismo volumen nombrado que creaste para mantener tus datos
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kcire -d dbLLM"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: fastapi_llm
    restart: always
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    environment:
      - APP_ENV=docker
      - OLLAMA_HOST=ollama
      - CHROMA_HOST=chroma
      - DB_HOST=postgres
      - MODEL_NAME=llama3.1:8b
      - PYTHONPATH=/app
    depends_on:
      postgres:
        condition: service_healthy 
      ollama:
        condition: service_started
      chroma:
        condition: service_started
    networks:
       - isolated_backend

volumes:
  ollama_data:
  chroma_data:
  postgres_data:

networks:
  isolated_backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24

